language: c#
sudo: false
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: npmjs@appcelerator.com
  api_key:
    secure: PsfkpJp/SwfC/0/4FTKNGqYascVEgnClwkQ+T/CL4Jwop+n5+PrylOd3ePvo+zO6TnRXK0KISHQschS0TopicpMQl3fzT4Cp+7QvO7329HL4a4AzA3JTzRB7lHBAjlTx6gDfyfVjMbLTM01kdSaLI5m/haa8K9GY22QM/ek5r0w=
  on:
    tags: true
    repo: appcelerator/windowslib
